<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <!-- Caster wheel joint and Link definition MACRO -->
    <xacro:macro name="caster_wheel" params="name radius mass dx dy offset height width">

        <!-- Caster Dimensions -->
        <xacro:property name="caster_wheel_length" value="${width}" />
        <xacro:property name="caster_wheel_radius" value="${radius}" />
        <xacro:property name="caster_base_length" value="${(height)-2*radius}" />
        <xacro:property name="caster_base_radius" value="${width}" />
        <xacro:property name="caster_base_joint_x" value="${dx}" />
        <xacro:property name="caster_base_joint_z" value="${dy}" />

        <link name="${name}_wheel_link">
            <collision>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}" />
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}" />
                </geometry>
                <material name="wheel" />
            </visual>

            <xacro:cylinder_inertia mass="${mass / 2}" radius="${caster_wheel_radius}" length="${caster_wheel_length}">
                <origin xyz="0 0 0" rpy="0 0 0" />
            </xacro:cylinder_inertia>
        </link>

        <link name="${name}_rotation_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${width}" length="${caster_base_length}" />
                </geometry>
                <material name="white" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${width}" length="${caster_base_length}" />
                </geometry>
            </collision>
            <xacro:cylinder_inertia mass="${mass / 2}" radius="${width}" length="${caster_base_length}">
                <origin xyz="0 0 0" rpy="0 0 0" />
            </xacro:cylinder_inertia>
        </link>


        <joint name="${name}_rotation_joint" type="fixed">
            <parent link="${robot_name}/base_link" />
            <child link="${name}_rotation_link" />
            <origin xyz="${dx} ${dy} ${(caster_base_length)/2 + 2*radius}" rpy="0 0 0" />
            <axis xyz="0 0 1" />
            <!-- <dynamics damping="0.00001" friction="1.0" /> -->
        </joint>

        <joint name="${name}_wheel_joint" type="fixed">
            <parent link="${name}_rotation_link" />
            <child link="${name}_wheel_link" />
            <origin xyz="${offset} 0 ${-(height)/2 }" rpy="0 0 0" />
            <axis xyz="0 1 0" />
            <!-- <dynamics damping="0.00001" friction="1.0" /> -->
        </joint>

        <transmission name="${name}_rotation_trans" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${name}_rotation_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${name}_rotation_joint">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
        </transmission>


        <transmission name="${name}_wheel_trans" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${name}_wheel_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${name}_wheel_joint">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
        </transmission>

    </xacro:macro>
</robot>