<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="chassis" params="name length width height clearence offset mass">

        <link name="${name}_link">
            <collision>
                <origin xyz="${offset} 0.0 ${height/2.0 + clearence}" rpy="0 0 0" />
                <geometry>
                    <box size="${length} ${width} ${height}" />
                </geometry>
            </collision>
            <visual>
                <origin xyz="${offset} 0.0 ${height/2.0 + clearence}" rpy="0.0 0.0 0.0" />
                <geometry>
                    <box size="${length} ${width} ${height}" />
                </geometry>
                <material name="chassis" />
            </visual>
            <xacro:cuboid_inertia x="${length}" y="${width}" z="${height}" mass="${mass}">
                <origin xyz="${offset} 0.0 ${height/2.0 + clearence}" rpy="0.0 0.0 0.0" />
            </xacro:cuboid_inertia>
        </link>

        <joint name="${name}_joint" type="fixed">
            <parent link="${robot_name}/base_footprint" />
            <child link="${name}_link" />
            <origin xyz="${offset} 0 0" rpy="0 0 0" />
            <axis xyz="0 1 0" rpy="0 0 0" />
        </joint>

    </xacro:macro>

</robot>