<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="chassis" params="name lenght width height clearence">

        <link name="${name}_link">
            <visual>
                <origin xyz="0.0 0.0 ${height/2.0 + clearence}" rpy="0.0 0.0 0.0" />
                <geometry>
                    <box size="${lenght} ${width} ${height}" />
                </geometry>
                <material name="chassis" />
            </visual>
        </link>

        <joint name="${name}_joint" type="fixed">
            <parent link="${robot_name}/base_footprint" />
            <child link="${name}_link" />
            <origin xyz="0 0 0" rpy="0 0 0" />
        </joint>

    </xacro:macro>

</robot>