imu:
  frame_id: "stm"
  name: "stm_imu"
  acceleration_covariance: [0.001, 0, 0, 0, 0.001, 0, 0, 0, 0.001]
  velocity_covariance: [0.001, 0, 0, 0, 0.001, 0, 0, 0, 0.001]
  orientation_covariance: [-1.0, 0, 0, 0, -1.0, 0, 0, 0, -1.0]
  gyro_offset: [-0.00940652984481903, -0.006390291507488461, 0.0016867405806967803]
  acc_offset: [-0.07408764347527157, -0.15995660294145872, 0.230708478]
  mag_offset: [0.0, 0.0, 0.0]
  mag_scale: [0.0, 0.0, 0.0]
  # mag_offset: [-644.25, 236.25, 731.4]
  # mag_scale: [1.0112138016019716, 1.0112138016019716, 0.9783023366714355]

motor_contoller:
  joint:
    left:
      name: "left_wheel"
      max_command: 10.0
      encoder_resolution: 256
    right:
      name: "right_wheel"
      max_command: 10.0
      encoder_resolution: 256

  pid:
    right:
      Kp: 0.1
      Ki: 0.0
      Kd: 0.0
      upperLimit: 0.0
      lowerLimit: 0.0
      alfa: 0.01
      windup: 0.0
      timeout: 5
      downLimitOn: false
      upLimitOn: false
      windupOn: false
    left:
      Kp: 0.1
      Ki: 0.0
      Kd: 0.0
      upperLimit: 0.0
      lowerLimit: 0.0
      alfa: 0.01
      windup: 0.0
      timeout: 5
      downLimitOn: false
      upLimitOn: false
      windupOn: false
