<?xml version="1.0"?>

<robot name="$(arg robot_name)" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find vc200_description)/urdf/parameters.xacro" />
    <xacro:include filename="$(find vc200_description)/urdf/macros/macros.xacro" />
    
    <link name="${robot_name}/base_footprint"/>
    

    <xacro:chassis 
      name="${robot_name}/base"
      lenght="${chassis_lenght}"
      width="${chassis_width}"
      height="${chassis_height}"
      clearence="${clearence}"
    />
    <xacro:wheel 
      name="${robot_name}/front_left_wheel"
      radius="${wheel_radius}"
      width="${wheel_width}"
      dx="${0.235/2.0}"
      dy="${wheel_separation/2.0}"
    />
    <xacro:wheel 
      name="${robot_name}/front_right_wheel"
      radius="${wheel_radius}"
      width="${wheel_width}"
      dx="${0.235/2.0}"
      dy="-${wheel_separation/2.0}"
    />
    <xacro:wheel 
      name="${robot_name}/rear_left_wheel"
      radius="${wheel_radius}"
      width="${wheel_width}"
      dx="-${0.235/2.0}"
      dy="${wheel_separation/2.0}"
    />
    <xacro:wheel 
      name="${robot_name}/rear_right_wheel"
      radius="${wheel_radius}"
      width="${wheel_width}"
      dx="-${0.235/2.0}"
      dy="-${wheel_separation/2.0}"
    />
</robot>
