<?xml version="1.0"?>

<!-- <robot name="$(arg robot_name)" xmlns:xacro="http://www.ros.org/wiki/xacro"> -->
<robot name="vc200" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find vc200_description)/urdf/parameters.xacro" />
    <xacro:include filename="$(find vc200_description)/urdf/macros/macros.xacro" />
    
    <link name="${robot_name}/base_footprint"/>
    

    <xacro:chassis 
      name="${robot_name}/base"
      length="${chassis_length}"
      width="${chassis_width}"
      height="${chassis_height}"
      clearence="${clearence}"
    />
    <xacro:wheel 
      name="${robot_name}/front_left_wheel"
      radius="${wheel_radius}"
      width="${wheel_width}"
      dx="${wheelbase/2.0}"
      dy="${wheel_separation/2.0}"
    />
    <xacro:wheel 
      name="${robot_name}/front_right_wheel"
      radius="${wheel_radius}"
      width="${wheel_width}"
      dx="${wheelbase/2.0}"
      dy="-${wheel_separation/2.0}"
    />
    <xacro:wheel 
      name="${robot_name}/rear_left_wheel"
      radius="${wheel_radius}"
      width="${wheel_width}"
      dx="-${wheelbase/2.0}"
      dy="${wheel_separation/2.0}"
    />
    <xacro:wheel 
      name="${robot_name}/rear_right_wheel"
      radius="${wheel_radius}"
      width="${wheel_width}"
      dx="-${wheelbase/2.0}"
      dy="-${wheel_separation/2.0}"
    />

  
    <xacro:lidar 
      name="${robot_name}/lidar"
      radius="0.035" 
      length="0.022" 
      dx="0.0425" 
      dy="0.0" 
      dz="0.205"
      ar="0.0" 
      ap="0.0" 
      ay="0.0"
    />
    <!-- radius="0.035" 
    length="0.0022"  -->

    <xacro:pozyx 
      name="${robot_name}/pozyx"
      length="0.008"
      width="0.006"
      height="0.003"
      dx="-0.025"
      dy="0.045"
      dz="${0.12+clearence+0.003/3}"
    />

    <xacro:marvelmind 
      name="${robot_name}/marvelmind"
      length ="0.055"
      width ="0.055"
      height ="0.033"
      dx="0.1575"
      dy="${-(chassis_width/2)+0.055/2+0.004}"
      dz="0.14"
      ar="0.0"
      ap="0.69813170079"
      ay="0.0"
    />
    <xacro:arg name="use_nominal_extrinsics" default="true" />
    <xacro:include filename="$(find vc200_description)/realsense2_description/urdf/_d435i.urdf.xacro"/>

    <!-- <link name="base_link" /> -->
    <xacro:sensor_d435i parent="${robot_name}/base_footprint" use_nominal_extrinsics="$(arg use_nominal_extrinsics)">
      <origin xyz="${chassis_length/2 + 0.0149} 0 0.135" rpy="0 0 0"/>
    </xacro:sensor_d435i>

</robot>
